// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_api.Lib.Database;

#nullable disable

namespace web_api.Migrations
{
    [DbContext(typeof(db_context))]
    [Migration("20251204161601_History")]
    partial class History
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("class_library.Models.Collection", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Private")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("class_library.Models.CollectionNote", b =>
                {
                    b.Property<Guid>("CollectionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NoteID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CollectionID", "NoteID");

                    b.HasIndex("NoteID");

                    b.ToTable("CollectionNotes", (string)null);
                });

            modelBuilder.Entity("class_library.Models.Institution", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Institutions", (string)null);
                });

            modelBuilder.Entity("class_library.Models.Log", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("class_library.Models.Note", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitutionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AuthorUserID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("class_library.Models.NoteHistory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NoteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.HasIndex("UserID");

                    b.ToTable("NoteHistories", (string)null);
                });

            modelBuilder.Entity("class_library.Models.NoteRating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NoteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.HasIndex("UserID");

                    b.ToTable("NoteRatings", (string)null);
                });

            modelBuilder.Entity("class_library.Models.NoteRequest", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CreatorUserID");

                    b.HasIndex("SubjectID");

                    b.ToTable("NoteRequests", (string)null);
                });

            modelBuilder.Entity("class_library.Models.NoteRequestAnswer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UploaderUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UploaderUserID");

                    b.ToTable("NoteRequestAnswers", (string)null);
                });

            modelBuilder.Entity("class_library.Models.Preference", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PrioritiseFollowedUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("PrioritiseInstructorNotes")
                        .HasColumnType("bit");

                    b.Property<bool>("PrioritiseRatedNotes")
                        .HasColumnType("bit");

                    b.Property<bool>("PrioritiseUsersFromInstitution")
                        .HasColumnType("bit");

                    b.Property<bool>("PrivateMyNotes")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Preferences", (string)null);
                });

            modelBuilder.Entity("class_library.Models.Subject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitutionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InstructorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeptunCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("InstructorID");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("class_library.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstitutionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.Property<Guid>("PreferenceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("PreferenceID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("class_library.Models.UserFollow", b =>
                {
                    b.Property<Guid>("FollowerUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowedUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FollowerUserID", "FollowedUserID");

                    b.HasIndex("FollowedUserID");

                    b.ToTable("UserFollows", (string)null);
                });

            modelBuilder.Entity("class_library.Models.UserSubject", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("UserSubjects", (string)null);
                });

            modelBuilder.Entity("class_library.Models.Collection", b =>
                {
                    b.HasOne("class_library.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("class_library.Models.CollectionNote", b =>
                {
                    b.HasOne("class_library.Models.Collection", "Collection")
                        .WithMany("CollectionNotes")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.Note", "Note")
                        .WithMany("CollectionNotes")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("class_library.Models.Note", b =>
                {
                    b.HasOne("class_library.Models.User", "Author")
                        .WithMany("Notes")
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.Institution", "Institution")
                        .WithMany("Notes")
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.Subject", "Subject")
                        .WithMany("Notes")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Institution");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("class_library.Models.NoteHistory", b =>
                {
                    b.HasOne("class_library.Models.Note", "ViewedNote")
                        .WithMany("NoteHistories")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.User", "Viewer")
                        .WithMany("NoteHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ViewedNote");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("class_library.Models.NoteRating", b =>
                {
                    b.HasOne("class_library.Models.Note", "Note")
                        .WithMany("Ratings")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.User", "User")
                        .WithMany("NoteRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("class_library.Models.NoteRequest", b =>
                {
                    b.HasOne("class_library.Models.User", "Creator")
                        .WithMany("NoteRequests")
                        .HasForeignKey("CreatorUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.Subject", "Subject")
                        .WithMany("NoteRequests")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("class_library.Models.NoteRequestAnswer", b =>
                {
                    b.HasOne("class_library.Models.NoteRequest", "Request")
                        .WithMany("Answers")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.User", "Uploader")
                        .WithMany("NoteRequestAnswers")
                        .HasForeignKey("UploaderUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("class_library.Models.Subject", b =>
                {
                    b.HasOne("class_library.Models.Institution", "Institution")
                        .WithMany("Subjects")
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Institution");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("class_library.Models.User", b =>
                {
                    b.HasOne("class_library.Models.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("class_library.Models.Preference", "Preference")
                        .WithMany()
                        .HasForeignKey("PreferenceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("class_library.Models.UserFollow", b =>
                {
                    b.HasOne("class_library.Models.User", "FollowedUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.User", "FollowerUser")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FollowedUser");

                    b.Navigation("FollowerUser");
                });

            modelBuilder.Entity("class_library.Models.UserSubject", b =>
                {
                    b.HasOne("class_library.Models.Subject", "Subject")
                        .WithMany("UserSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("class_library.Models.User", "User")
                        .WithMany("UserSubjects")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("class_library.Models.Collection", b =>
                {
                    b.Navigation("CollectionNotes");
                });

            modelBuilder.Entity("class_library.Models.Institution", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("class_library.Models.Note", b =>
                {
                    b.Navigation("CollectionNotes");

                    b.Navigation("NoteHistories");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("class_library.Models.NoteRequest", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("class_library.Models.Subject", b =>
                {
                    b.Navigation("NoteRequests");

                    b.Navigation("Notes");

                    b.Navigation("UserSubjects");
                });

            modelBuilder.Entity("class_library.Models.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("NoteHistories");

                    b.Navigation("NoteRatings");

                    b.Navigation("NoteRequestAnswers");

                    b.Navigation("NoteRequests");

                    b.Navigation("Notes");

                    b.Navigation("UserSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
