name: .NET Backend CI/CD

on:
  push:
    paths:
      - 'Backend/**'
      - '.github/workflows/dotnet.yml'
  pull_request:
    paths:
      - 'Backend/**'
      - '.github/workflows/dotnet.yml'

defaults:
  run:
    working-directory: Backend/NoteSharingAPI

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore NoteSharingAPI.sln

    - name: Build
      run: dotnet build NoteSharingAPI.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish web_api/web_api.csproj --configuration Release --output ./publish --no-build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: Backend/NoteSharingAPI/publish/
        retention-days: 30
